name: 'user-web'
port: 8021
user_srv:
  host: '192.168.0.112'
  port: 50051
  name: 'user-srv'

jwt:
  key: '123456'

redis:
  host: '47.106.214.127'
  port: 6379

sms:
  key: ''
  secret: ''

consul:
  host: '192.168.121.136'
  port: 8500